### ISSUE TITLE
Hide size for every node

### ISSUE THREAD

**Issue by RosaRomeroGomez** [jquintozamora/react-d3-treemap#13]
Is there a way to remove showing the value number for each node? I just care about the number of childrens every node has but I don't care about the size of every node.

**Comment by jakubfiala-bbc** [comment]
@RosaRomeroGomez this is a bit hacky but you could hide it with CSS:

```
text tspan:last-of-type {
  display: none;
}
```

**Comment by jquintozamora** [comment]
Hi @RosaRomeroGomez ,
Sorry for late answer. 
I've updated the npm package enabling hideValue and hideNumberOfChildren. 
You can see an example [here](https://github.com/jquintozamora/react-d3-treemap/blob/master/src/containers/App.tsx)

Note: please update version to react-d3-treemap@1.0.13

Please let me know if that solve your issue.
