### ISSUE TITLE
Triggering Treemap update on data refresh

### ISSUE THREAD

**Issue by rayhooker** [jquintozamora/react-d3-treemap#43]
Has anyone gotten the Treemap to refresh when changing the data map?  I want to have two views and switch dynamically but the treemap does not refresh.  Thoughts or suggestions?

**Comment by jerdobi** [comment]
I have the same question on after changing the data, the UI doesn't automatically refresh and you have to manually click into the treemap.  Is there a way for this to happen by ?

**Comment by jquintozamora** [comment]
Hello @rayhooker , @jerdobi , 
Could you please share your code for updating the date, then I'd have better idea on how to achieve it.

Thanks!

**Comment by jquintozamora** [comment]
I have updated `react-d3-treemap` to version `1.0.15`. So, now you should be able to get the data refresh. Please let me know if it works.
