### ISSUE TITLE
Animation doesn't seem to be working

### ISSUE THREAD

**Issue by japhex** [jquintozamora/react-d3-treemap#44]
The zoom animation when click on a node doesn't seem to be working by default, is there something that has to be specific as a prop?

Thanks in advance, this is fantastic!

**Comment by jquintozamora** [comment]
That's a component named: NodeContainer.Animated , you can use it instead of NodeContainer.

I'm working on refactoring it....

**Comment by jquintozamora** [comment]
I've disabled animation for now, as it was giving some issues.
