### ISSUE TITLE
Wrong size of children rectangles

### ISSUE THREAD

**Issue by DominikZabron** [jquintozamora/react-d3-treemap#50]
Rectangles do not fill the whole area of the parent, but only a small part at the bottom. 

![Screenshot](https://user-images.githubusercontent.com/16049942/78132447-0bdb0c80-741d-11ea-9c27-21ddd0cc0ff5.png)

Please advise how to fix this.

**Comment by jquintozamora** [comment]
You have 2 scale functions so you can play with it:

```
 xScaleFunction: scaleLinear().range([0, this.props.width]),
 yScaleFunction: scaleLinear().range([0, this.props.height]),
```

**Comment by jquintozamora** [comment]
I've expose also a prop called `paddingInner` so you can configure the padding between nodes
