### ISSUE TITLE
Override text splitting mechanism for leaf nodes

### ISSUE THREAD

**Issue by xandaschofield** [jquintozamora/react-d3-treemap#63]
https://github.com/jquintozamora/react-d3-treemap/blob/11fdef948b2fd6bc9f44ebf16bcff4875b178793/src/components/Node/LabelNewLine/LabelNewLine.tsx#L36

Right now, nodes without children split the text using a regular expression. Unfortunately, this regular expression doesn't always produce natural-looking splits for visualization (for instance, it splits "it's" into "i" and "t's"). It'd be nice to be able to override this behavior in some way, either with an alternate split regular expression or just with a boolean to disable the split.

(PS: thank you for implementing this treemap, it's nice!)

**Comment by jquintozamora** [comment]
Hey @xandaschofield ,

Thanks for your suggestion, providing a way to override RegEx looks easy path to go. 

Created new version, so you can use `splitRegExp` prop: `react-d3-treemap@1.0.28`

**Comment by xandaschofield** [comment]
Amazing, thank you!
