### ISSUE TITLE
Why the extra margin between nodes, especially at deeper levels?

### ISSUE THREAD

**Issue by thomasjm** [jquintozamora/react-d3-treemap#69]
I'm seeing this issue where there is a large margin around the nodes sometimes, especially when you zoom to deeper levels of the hierarchy.

This happens a couple times in the GIF of this repo's own README (see below).

This is confusing to me because it doesn't match my understanding of how a treemap should work. The sub-nodes should sum to 100% of the area of the parent node, right? We should only leave a little extra margin near the top so that the label is visible.

(In principle it's possible for the parent node to have extra "value" of its own, which would explain why the children wouldn't fully cover its area. But this isn't the case for the examples I'm seeing with my own data, which makes this seem like a bug.)

I tried various settings like `paddingInner=0` to try to fix this, but no luck.

![image](https://github.com/jquintozamora/react-d3-treemap/assets/1634990/3b22675a-1a5a-458f-83ad-6a905f23ab27)

![image](https://github.com/jquintozamora/react-d3-treemap/assets/1634990/e0e3bd09-07ca-4933-88c9-27ad59a752e5)

**Comment by thomasjm** [comment]
Oh, I have a fix on my fork. The main commit is here:

https://github.com/jquintozamora/react-d3-treemap/commit/411571707abb473d608d0cdc19a27064f93d980d

Here's my branch in case it helps:

https://github.com/codedownio/react-d3-treemap/tree/depth-padding-control

**Comment by jquintozamora** [comment]
Thanks @thomasjm , there were few more bugs that I solved in version 2.0.2. 

Please let me know if you are missing something.
